package com.triz.goldenideabox.model;

import java.io.Serializable;

public class Chart implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chart.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chart.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chart.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chart.template_id
     *
     * @mbg.generated
     */
    private Integer templateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chart.filter
     *
     * @mbg.generated
     */
    private String filter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chart.property1
     *
     * @mbg.generated
     */
    private Integer property1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chart.property2
     *
     * @mbg.generated
     */
    private Integer property2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chart.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_chart.express
     *
     * @mbg.generated
     */
    private Integer scope;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_chart
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chart.id
     *
     * @return the value of t_chart.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chart.id
     *
     * @param id the value for t_chart.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chart.user_id
     *
     * @return the value of t_chart.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chart.user_id
     *
     * @param userId the value for t_chart.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chart.name
     *
     * @return the value of t_chart.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chart.name
     *
     * @param name the value for t_chart.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chart.template_id
     *
     * @return the value of t_chart.template_id
     *
     * @mbg.generated
     */
    public Integer getTemplateId() {
        return templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chart.template_id
     *
     * @param templateId the value for t_chart.template_id
     *
     * @mbg.generated
     */
    public void setTemplateId(Integer templateId) {
        this.templateId = templateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chart.filter
     *
     * @return the value of t_chart.filter
     *
     * @mbg.generated
     */
    public String getFilter() {
        return filter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chart.filter
     *
     * @param filter the value for t_chart.filter
     *
     * @mbg.generated
     */
    public void setFilter(String filter) {
        this.filter = filter == null ? null : filter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chart.property1
     *
     * @return the value of t_chart.property1
     *
     * @mbg.generated
     */
    public Integer getProperty1() {
        return property1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chart.property1
     *
     * @param property1 the value for t_chart.property1
     *
     * @mbg.generated
     */
    public void setProperty1(Integer property1) {
        this.property1 = property1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chart.property2
     *
     * @return the value of t_chart.property2
     *
     * @mbg.generated
     */
    public Integer getProperty2() {
        return property2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chart.property2
     *
     * @param property2 the value for t_chart.property2
     *
     * @mbg.generated
     */
    public void setProperty2(Integer property2) {
        this.property2 = property2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chart.type
     *
     * @return the value of t_chart.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chart.type
     *
     * @param type the value for t_chart.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_chart.express
     *
     * @return the value of t_chart.express
     *
     * @mbg.generated
     */
    public Integer getScope() {
        return scope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_chart.express
     *
     * @param scope the value for t_chart.express
     *
     * @mbg.generated
     */
    public void setScope(Integer scope) {
        this.scope = scope;
    }
}