package com.triz.goldenideabox.model;

import java.io.Serializable;

public class CpqueryApplicationInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_application_info.application_number
     *
     * @mbg.generated
     */
    private String applicationNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_application_info.application_date
     *
     * @mbg.generated
     */
    private String applicationDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_application_info.case_status
     *
     * @mbg.generated
     */
    private String caseStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_application_info.main_category_number
     *
     * @mbg.generated
     */
    private String mainCategoryNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_application_info.submission_date
     *
     * @mbg.generated
     */
    private String submissionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_application_info.applicant
     *
     * @mbg.generated
     */
    private String applicant;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_application_info.inventor
     *
     * @mbg.generated
     */
    private String inventor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_application_info.agency
     *
     * @mbg.generated
     */
    private String agency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_application_info.first_agent
     *
     * @mbg.generated
     */
    private String firstAgent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_application_info.project_change
     *
     * @mbg.generated
     */
    private String projectChange;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cpquery_application_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_application_info.application_number
     *
     * @return the value of t_cpquery_application_info.application_number
     *
     * @mbg.generated
     */
    public String getApplicationNumber() {
        return applicationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_application_info.application_number
     *
     * @param applicationNumber the value for t_cpquery_application_info.application_number
     *
     * @mbg.generated
     */
    public void setApplicationNumber(String applicationNumber) {
        this.applicationNumber = applicationNumber == null ? null : applicationNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_application_info.application_date
     *
     * @return the value of t_cpquery_application_info.application_date
     *
     * @mbg.generated
     */
    public String getApplicationDate() {
        return applicationDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_application_info.application_date
     *
     * @param applicationDate the value for t_cpquery_application_info.application_date
     *
     * @mbg.generated
     */
    public void setApplicationDate(String applicationDate) {
        this.applicationDate = applicationDate == null ? null : applicationDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_application_info.case_status
     *
     * @return the value of t_cpquery_application_info.case_status
     *
     * @mbg.generated
     */
    public String getCaseStatus() {
        return caseStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_application_info.case_status
     *
     * @param caseStatus the value for t_cpquery_application_info.case_status
     *
     * @mbg.generated
     */
    public void setCaseStatus(String caseStatus) {
        this.caseStatus = caseStatus == null ? null : caseStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_application_info.main_category_number
     *
     * @return the value of t_cpquery_application_info.main_category_number
     *
     * @mbg.generated
     */
    public String getMainCategoryNumber() {
        return mainCategoryNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_application_info.main_category_number
     *
     * @param mainCategoryNumber the value for t_cpquery_application_info.main_category_number
     *
     * @mbg.generated
     */
    public void setMainCategoryNumber(String mainCategoryNumber) {
        this.mainCategoryNumber = mainCategoryNumber == null ? null : mainCategoryNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_application_info.submission_date
     *
     * @return the value of t_cpquery_application_info.submission_date
     *
     * @mbg.generated
     */
    public String getSubmissionDate() {
        return submissionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_application_info.submission_date
     *
     * @param submissionDate the value for t_cpquery_application_info.submission_date
     *
     * @mbg.generated
     */
    public void setSubmissionDate(String submissionDate) {
        this.submissionDate = submissionDate == null ? null : submissionDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_application_info.applicant
     *
     * @return the value of t_cpquery_application_info.applicant
     *
     * @mbg.generated
     */
    public String getApplicant() {
        return applicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_application_info.applicant
     *
     * @param applicant the value for t_cpquery_application_info.applicant
     *
     * @mbg.generated
     */
    public void setApplicant(String applicant) {
        this.applicant = applicant == null ? null : applicant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_application_info.inventor
     *
     * @return the value of t_cpquery_application_info.inventor
     *
     * @mbg.generated
     */
    public String getInventor() {
        return inventor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_application_info.inventor
     *
     * @param inventor the value for t_cpquery_application_info.inventor
     *
     * @mbg.generated
     */
    public void setInventor(String inventor) {
        this.inventor = inventor == null ? null : inventor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_application_info.agency
     *
     * @return the value of t_cpquery_application_info.agency
     *
     * @mbg.generated
     */
    public String getAgency() {
        return agency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_application_info.agency
     *
     * @param agency the value for t_cpquery_application_info.agency
     *
     * @mbg.generated
     */
    public void setAgency(String agency) {
        this.agency = agency == null ? null : agency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_application_info.first_agent
     *
     * @return the value of t_cpquery_application_info.first_agent
     *
     * @mbg.generated
     */
    public String getFirstAgent() {
        return firstAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_application_info.first_agent
     *
     * @param firstAgent the value for t_cpquery_application_info.first_agent
     *
     * @mbg.generated
     */
    public void setFirstAgent(String firstAgent) {
        this.firstAgent = firstAgent == null ? null : firstAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_application_info.project_change
     *
     * @return the value of t_cpquery_application_info.project_change
     *
     * @mbg.generated
     */
    public String getProjectChange() {
        return projectChange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_application_info.project_change
     *
     * @param projectChange the value for t_cpquery_application_info.project_change
     *
     * @mbg.generated
     */
    public void setProjectChange(String projectChange) {
        this.projectChange = projectChange == null ? null : projectChange.trim();
    }


    @Override
    public String toString() {
        return "CpqueryApplicationInfo{" +
                "applicationNumber='" + applicationNumber + '\'' +
                ", applicationDate='" + applicationDate + '\'' +
                ", caseStatus='" + caseStatus + '\'' +
                ", mainCategoryNumber='" + mainCategoryNumber + '\'' +
                ", submissionDate='" + submissionDate + '\'' +
                ", applicant='" + applicant + '\'' +
                ", inventor='" + inventor + '\'' +
                ", agency='" + agency + '\'' +
                ", firstAgent='" + firstAgent + '\'' +
                ", projectChange='" + projectChange + '\'' +
                '}';
    }
}