package com.triz.goldenideabox.model;

import java.io.Serializable;

public class CpqueryPostInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_post_info.application_number
     *
     * @mbg.generated
     */
    private String applicationNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_post_info.notice
     *
     * @mbg.generated
     */
    private String notice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_post_info.patent_certificate
     *
     * @mbg.generated
     */
    private String patentCertificate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_post_info.bounce
     *
     * @mbg.generated
     */
    private String bounce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cpquery_post_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_post_info.application_number
     *
     * @return the value of t_cpquery_post_info.application_number
     *
     * @mbg.generated
     */
    public String getApplicationNumber() {
        return applicationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_post_info.application_number
     *
     * @param applicationNumber the value for t_cpquery_post_info.application_number
     *
     * @mbg.generated
     */
    public void setApplicationNumber(String applicationNumber) {
        this.applicationNumber = applicationNumber == null ? null : applicationNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_post_info.notice
     *
     * @return the value of t_cpquery_post_info.notice
     *
     * @mbg.generated
     */
    public String getNotice() {
        return notice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_post_info.notice
     *
     * @param notice the value for t_cpquery_post_info.notice
     *
     * @mbg.generated
     */
    public void setNotice(String notice) {
        this.notice = notice == null ? null : notice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_post_info.patent_certificate
     *
     * @return the value of t_cpquery_post_info.patent_certificate
     *
     * @mbg.generated
     */
    public String getPatentCertificate() {
        return patentCertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_post_info.patent_certificate
     *
     * @param patentCertificate the value for t_cpquery_post_info.patent_certificate
     *
     * @mbg.generated
     */
    public void setPatentCertificate(String patentCertificate) {
        this.patentCertificate = patentCertificate == null ? null : patentCertificate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_post_info.bounce
     *
     * @return the value of t_cpquery_post_info.bounce
     *
     * @mbg.generated
     */
    public String getBounce() {
        return bounce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_post_info.bounce
     *
     * @param bounce the value for t_cpquery_post_info.bounce
     *
     * @mbg.generated
     */
    public void setBounce(String bounce) {
        this.bounce = bounce == null ? null : bounce.trim();
    }
}