package com.triz.goldenideabox.model;

import java.io.Serializable;

public class CpqueryCostInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_cost_info.application_number
     *
     * @mbg.generated
     */
    private String applicationNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_cost_info.payable
     *
     * @mbg.generated
     */
    private String payable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_cost_info.paid
     *
     * @mbg.generated
     */
    private String paid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_cost_info.refund
     *
     * @mbg.generated
     */
    private String refund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_cost_info.forfeit
     *
     * @mbg.generated
     */
    private String forfeit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_cost_info.receipt
     *
     * @mbg.generated
     */
    private String receipt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cpquery_cost_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_cost_info.application_number
     *
     * @return the value of t_cpquery_cost_info.application_number
     *
     * @mbg.generated
     */
    public String getApplicationNumber() {
        return applicationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_cost_info.application_number
     *
     * @param applicationNumber the value for t_cpquery_cost_info.application_number
     *
     * @mbg.generated
     */
    public void setApplicationNumber(String applicationNumber) {
        this.applicationNumber = applicationNumber == null ? null : applicationNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_cost_info.payable
     *
     * @return the value of t_cpquery_cost_info.payable
     *
     * @mbg.generated
     */
    public String getPayable() {
        return payable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_cost_info.payable
     *
     * @param payable the value for t_cpquery_cost_info.payable
     *
     * @mbg.generated
     */
    public void setPayable(String payable) {
        this.payable = payable == null ? null : payable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_cost_info.paid
     *
     * @return the value of t_cpquery_cost_info.paid
     *
     * @mbg.generated
     */
    public String getPaid() {
        return paid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_cost_info.paid
     *
     * @param paid the value for t_cpquery_cost_info.paid
     *
     * @mbg.generated
     */
    public void setPaid(String paid) {
        this.paid = paid == null ? null : paid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_cost_info.refund
     *
     * @return the value of t_cpquery_cost_info.refund
     *
     * @mbg.generated
     */
    public String getRefund() {
        return refund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_cost_info.refund
     *
     * @param refund the value for t_cpquery_cost_info.refund
     *
     * @mbg.generated
     */
    public void setRefund(String refund) {
        this.refund = refund == null ? null : refund.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_cost_info.forfeit
     *
     * @return the value of t_cpquery_cost_info.forfeit
     *
     * @mbg.generated
     */
    public String getForfeit() {
        return forfeit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_cost_info.forfeit
     *
     * @param forfeit the value for t_cpquery_cost_info.forfeit
     *
     * @mbg.generated
     */
    public void setForfeit(String forfeit) {
        this.forfeit = forfeit == null ? null : forfeit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_cost_info.receipt
     *
     * @return the value of t_cpquery_cost_info.receipt
     *
     * @mbg.generated
     */
    public String getReceipt() {
        return receipt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_cost_info.receipt
     *
     * @param receipt the value for t_cpquery_cost_info.receipt
     *
     * @mbg.generated
     */
    public void setReceipt(String receipt) {
        this.receipt = receipt == null ? null : receipt.trim();
    }
}