package com.triz.goldenideabox.model;

import java.io.Serializable;
import java.util.Date;

public class CpqueryResult implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_result.application_number
     *
     * @mbg.generated
     */
    private String applicationNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_result.cpquery_id
     *
     * @mbg.generated
     */
    private Integer cpqueryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_result.patent_id
     *
     * @mbg.generated
     */
    private Integer patentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_result.application_status
     *
     * @mbg.generated
     */
    private Integer applicationStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_result.review_status
     *
     * @mbg.generated
     */
    private Integer reviewStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_result.cost_status
     *
     * @mbg.generated
     */
    private Integer costStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_result.post_status
     *
     * @mbg.generated
     */
    private Integer postStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_result.announce_status
     *
     * @mbg.generated
     */
    private Integer announceStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_result.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_result.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cpquery_result
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_result.application_number
     *
     * @return the value of t_cpquery_result.application_number
     *
     * @mbg.generated
     */
    public String getApplicationNumber() {
        return applicationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_result.application_number
     *
     * @param applicationNumber the value for t_cpquery_result.application_number
     *
     * @mbg.generated
     */
    public void setApplicationNumber(String applicationNumber) {
        this.applicationNumber = applicationNumber == null ? null : applicationNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_result.cpquery_id
     *
     * @return the value of t_cpquery_result.cpquery_id
     *
     * @mbg.generated
     */
    public Integer getCpqueryId() {
        return cpqueryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_result.cpquery_id
     *
     * @param cpqueryId the value for t_cpquery_result.cpquery_id
     *
     * @mbg.generated
     */
    public void setCpqueryId(Integer cpqueryId) {
        this.cpqueryId = cpqueryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_result.patent_id
     *
     * @return the value of t_cpquery_result.patent_id
     *
     * @mbg.generated
     */
    public Integer getPatentId() {
        return patentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_result.patent_id
     *
     * @param patentId the value for t_cpquery_result.patent_id
     *
     * @mbg.generated
     */
    public void setPatentId(Integer patentId) {
        this.patentId = patentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_result.application_status
     *
     * @return the value of t_cpquery_result.application_status
     *
     * @mbg.generated
     */
    public Integer getApplicationStatus() {
        return applicationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_result.application_status
     *
     * @param applicationStatus the value for t_cpquery_result.application_status
     *
     * @mbg.generated
     */
    public void setApplicationStatus(Integer applicationStatus) {
        this.applicationStatus = applicationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_result.review_status
     *
     * @return the value of t_cpquery_result.review_status
     *
     * @mbg.generated
     */
    public Integer getReviewStatus() {
        return reviewStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_result.review_status
     *
     * @param reviewStatus the value for t_cpquery_result.review_status
     *
     * @mbg.generated
     */
    public void setReviewStatus(Integer reviewStatus) {
        this.reviewStatus = reviewStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_result.cost_status
     *
     * @return the value of t_cpquery_result.cost_status
     *
     * @mbg.generated
     */
    public Integer getCostStatus() {
        return costStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_result.cost_status
     *
     * @param costStatus the value for t_cpquery_result.cost_status
     *
     * @mbg.generated
     */
    public void setCostStatus(Integer costStatus) {
        this.costStatus = costStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_result.post_status
     *
     * @return the value of t_cpquery_result.post_status
     *
     * @mbg.generated
     */
    public Integer getPostStatus() {
        return postStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_result.post_status
     *
     * @param postStatus the value for t_cpquery_result.post_status
     *
     * @mbg.generated
     */
    public void setPostStatus(Integer postStatus) {
        this.postStatus = postStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_result.announce_status
     *
     * @return the value of t_cpquery_result.announce_status
     *
     * @mbg.generated
     */
    public Integer getAnnounceStatus() {
        return announceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_result.announce_status
     *
     * @param announceStatus the value for t_cpquery_result.announce_status
     *
     * @mbg.generated
     */
    public void setAnnounceStatus(Integer announceStatus) {
        this.announceStatus = announceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_result.update_time
     *
     * @return the value of t_cpquery_result.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_result.update_time
     *
     * @param updateTime the value for t_cpquery_result.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_result.remark
     *
     * @return the value of t_cpquery_result.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_result.remark
     *
     * @param remark the value for t_cpquery_result.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}