package com.triz.goldenideabox.model;

import java.io.Serializable;
import java.util.Date;

public class CpqueryResult implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_result.cpquery_id
     *
     * @mbg.generated
     */
    private Integer cpqueryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_result.patent_id
     *
     * @mbg.generated
     */
    private Integer patentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_result.application_number
     *
     * @mbg.generated
     */
    private String applicationNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_result.official_status
     *
     * @mbg.generated
     */
    private String officialStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_result.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_result.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_result.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cpquery_result
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_result.cpquery_id
     *
     * @return the value of t_cpquery_result.cpquery_id
     *
     * @mbg.generated
     */
    public Integer getCpqueryId() {
        return cpqueryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_result.cpquery_id
     *
     * @param cpqueryId the value for t_cpquery_result.cpquery_id
     *
     * @mbg.generated
     */
    public void setCpqueryId(Integer cpqueryId) {
        this.cpqueryId = cpqueryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_result.patent_id
     *
     * @return the value of t_cpquery_result.patent_id
     *
     * @mbg.generated
     */
    public Integer getPatentId() {
        return patentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_result.patent_id
     *
     * @param patentId the value for t_cpquery_result.patent_id
     *
     * @mbg.generated
     */
    public void setPatentId(Integer patentId) {
        this.patentId = patentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_result.application_number
     *
     * @return the value of t_cpquery_result.application_number
     *
     * @mbg.generated
     */
    public String getApplicationNumber() {
        return applicationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_result.application_number
     *
     * @param applicationNumber the value for t_cpquery_result.application_number
     *
     * @mbg.generated
     */
    public void setApplicationNumber(String applicationNumber) {
        this.applicationNumber = applicationNumber == null ? null : applicationNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_result.official_status
     *
     * @return the value of t_cpquery_result.official_status
     *
     * @mbg.generated
     */
    public String getOfficialStatus() {
        return officialStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_result.official_status
     *
     * @param officialStatus the value for t_cpquery_result.official_status
     *
     * @mbg.generated
     */
    public void setOfficialStatus(String officialStatus) {
        this.officialStatus = officialStatus == null ? null : officialStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_result.create_time
     *
     * @return the value of t_cpquery_result.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_result.create_time
     *
     * @param createTime the value for t_cpquery_result.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_result.update_time
     *
     * @return the value of t_cpquery_result.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_result.update_time
     *
     * @param updateTime the value for t_cpquery_result.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_result.status
     *
     * @return the value of t_cpquery_result.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_result.status
     *
     * @param status the value for t_cpquery_result.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}