package com.triz.goldenideabox.model;

import java.io.Serializable;

public class CpqueryAnnounceInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_announce_info.application_number
     *
     * @mbg.generated
     */
    private String applicationNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_announce_info.publish
     *
     * @mbg.generated
     */
    private String publish;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cpquery_announce_info.transaction_publish
     *
     * @mbg.generated
     */
    private String transactionPublish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_cpquery_announce_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_announce_info.application_number
     *
     * @return the value of t_cpquery_announce_info.application_number
     *
     * @mbg.generated
     */
    public String getApplicationNumber() {
        return applicationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_announce_info.application_number
     *
     * @param applicationNumber the value for t_cpquery_announce_info.application_number
     *
     * @mbg.generated
     */
    public void setApplicationNumber(String applicationNumber) {
        this.applicationNumber = applicationNumber == null ? null : applicationNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_announce_info.publish
     *
     * @return the value of t_cpquery_announce_info.publish
     *
     * @mbg.generated
     */
    public String getPublish() {
        return publish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_announce_info.publish
     *
     * @param publish the value for t_cpquery_announce_info.publish
     *
     * @mbg.generated
     */
    public void setPublish(String publish) {
        this.publish = publish == null ? null : publish.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cpquery_announce_info.transaction_publish
     *
     * @return the value of t_cpquery_announce_info.transaction_publish
     *
     * @mbg.generated
     */
    public String getTransactionPublish() {
        return transactionPublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cpquery_announce_info.transaction_publish
     *
     * @param transactionPublish the value for t_cpquery_announce_info.transaction_publish
     *
     * @mbg.generated
     */
    public void setTransactionPublish(String transactionPublish) {
        this.transactionPublish = transactionPublish == null ? null : transactionPublish.trim();
    }
}