package com.triz.goldenideabox.dao;

import com.triz.goldenideabox.model.CpqueryReviewInfo;
import java.util.List;

public interface CpqueryReviewInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_review_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_review_info
     *
     * @mbg.generated
     */
    int insert(CpqueryReviewInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_review_info
     *
     * @mbg.generated
     */
    int insertSelective(CpqueryReviewInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_review_info
     *
     * @mbg.generated
     */
    CpqueryReviewInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_review_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CpqueryReviewInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_review_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CpqueryReviewInfo record);

    List<String> selectIdListByApplicationNumber(String applicationNumber);

    List<CpqueryReviewInfo> selectFileListByApplicationNumber(String applicationNumber);
}