package com.triz.goldenideabox.dao;

import com.triz.goldenideabox.model.CpqueryAnnounceInfo;

public interface CpqueryAnnounceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_announce_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String applicationNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_announce_info
     *
     * @mbg.generated
     */
    int insert(CpqueryAnnounceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_announce_info
     *
     * @mbg.generated
     */
    int insertSelective(CpqueryAnnounceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_announce_info
     *
     * @mbg.generated
     */
    CpqueryAnnounceInfo selectByPrimaryKey(String applicationNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_announce_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CpqueryAnnounceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_announce_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CpqueryAnnounceInfo record);
}