package com.triz.goldenideabox.dao;


import com.triz.goldenideabox.model.Cpquery;
import com.triz.goldenideabox.model.CpqueryResult;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CpqueryResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_result
     *
     * @mbg.generated
     */
    int insert(CpqueryResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_result
     *
     * @mbg.generated
     */
    int insertSelective(CpqueryResult record);



    List<CpqueryResult> getApplicationNumbers(Integer id);

    int updateResult(CpqueryResult cpqueryResult);

    int updateApplicationNumbers(@Param("id")Integer id, @Param("templateId")Integer templateId,
        @Param("matchField")Integer matchField, @Param("matchChar")String matchChar,
        @Param("applicationNumberField")Integer applicationNumberField,@Param("statusField")Integer statusField);

    int deleteExpiredData(Integer num);

    List<CpqueryResult> getCpqueryResult();

    List<CpqueryResult> getCpqueryResultByDay(@Param("cpqueryId")Integer cpqueryId,@Param("day")String day);
}