package com.triz.goldenideabox.dao;

import com.triz.goldenideabox.model.CpqueryPostInfo;

public interface CpqueryPostInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_post_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String applicationNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_post_info
     *
     * @mbg.generated
     */
    int insert(CpqueryPostInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_post_info
     *
     * @mbg.generated
     */
    int insertSelective(CpqueryPostInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_post_info
     *
     * @mbg.generated
     */
    CpqueryPostInfo selectByPrimaryKey(String applicationNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_post_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CpqueryPostInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_post_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CpqueryPostInfo record);
}