package com.triz.goldenideabox.dao;

import com.triz.goldenideabox.model.CpqueryCostInfo;

public interface CpqueryCostInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_cost_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String applicationNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_cost_info
     *
     * @mbg.generated
     */
    int insert(CpqueryCostInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_cost_info
     *
     * @mbg.generated
     */
    int insertSelective(CpqueryCostInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_cost_info
     *
     * @mbg.generated
     */
    CpqueryCostInfo selectByPrimaryKey(String applicationNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_cost_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CpqueryCostInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_cost_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CpqueryCostInfo record);
}