package com.triz.goldenideabox.dao;

import com.triz.goldenideabox.model.CpqueryApplicationInfo;

public interface CpqueryApplicationInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_application_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String applicationNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_application_info
     *
     * @mbg.generated
     */
    int insert(CpqueryApplicationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_application_info
     *
     * @mbg.generated
     */
    int insertSelective(CpqueryApplicationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_application_info
     *
     * @mbg.generated
     */
    CpqueryApplicationInfo selectByPrimaryKey(String applicationNumber);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_application_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CpqueryApplicationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_application_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(CpqueryApplicationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cpquery_application_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CpqueryApplicationInfo record);
}