package com.triz.goldenideabox.dao;


import com.triz.goldenideabox.model.IndexSetting;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface IndexSettingMapper {



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_index_setting
     *
     * @mbg.generated
     */
    int insert(IndexSetting record);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_index_setting
     *
     * @mbg.generated
     */
    IndexSetting selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_index_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(IndexSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_index_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(IndexSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_index_setting
     *
     * @mbg.generated
     */
    int addIndexSetting(IndexSetting record);

    List<IndexSetting> getIndexSetting(Integer userId);

    int deleteIndexSetting(Integer id);

    int sortIndexSetting(@Param("lst")List<Integer> lst);
}