package com.triz.goldenideabox.dao;

import com.alibaba.fastjson.JSONObject;
import com.triz.goldenideabox.model.Message;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated
     */
    int insert(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated
     */
    int insertSelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated
     */
    Message selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Message record);

    List<JSONObject> selectChatUser(Integer id);

    List<Message> selectChatUserRecord(@Param("userId")Integer userId,@Param("chatId")Integer chatId);

    List<JSONObject> selectChatGroup(@Param("id")Integer id, @Param("time")Date time);

    List<JSONObject> selectChatGroupRecord(@Param("groupId")Integer groupId);

    int changeUnread(@Param("userId")Integer userId, @Param("chatId")Integer chatId);
}