package com.triz.goldenideabox.dao;

import com.triz.goldenideabox.model.OperationLog;
import java.util.List;

public interface OperationLogMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_log
     *
     * @mbg.generated
     */
    int insert(OperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_log
     *
     * @mbg.generated
     */
    OperationLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OperationLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operation_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OperationLog record);


    List<OperationLog> selectByCategory(Integer category);

    int deleteExpiredLog(Integer day);
}